[workspace]
resolver = "3"
members = [
    "r503",
    "r503-cli",
    "r503-mock",
    "examples/rp2040",
]

[workspace.package]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
embedded-io-async = "0.7.0"
defmt = "1.1"

[profile.release]
# Enable generation of debug symbols even on release builds
debug = true
