name: Rust (lint, build, test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Install Rust components
       run: rustup component add clippy rustfmt
     - name: Install libudev-dev
       run: sudo apt-get -y install libudev-dev
     - name: rustfmt check
       run: cargo fmt --all -- --check
     - name: clippy (deny warnings)
       run: |
         cargo clippy --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install libudev-dev
      run: sudo apt-get -y install libudev-dev
    - name: Cargo Build
      run: cargo build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install libudev-dev
      run: sudo apt-get -y install libudev-dev
    - name: Run tests
      run: cargo test --all-features
  check-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-readme
      run: cargo install --git https://github.com/webern/cargo-readme.git --rev 9e8b9866e82289bc38c854171907df639dcdc66e --locked cargo-readme
    - name: Check readme
      run: |
        cd r503
        cargo readme --no-indent-headings --no-license --no-title -o /tmp/README.md
        diff -q README.md /tmp/README.md
